services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - ./.env 
    volumes:
      - pgdata:/var/lib/postgresql/data  # Persistent storage
    ports:
      - "5431:5432"
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file:
      - ./.env  # Using .env for pgAdmin credentials
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - my_network

volumes:
  pgdata:
    driver: local

networks:
  my_network:
    driver: bridge